#pragma once

#include <filesystem>
#include <fstream>
#include <iostream>
#include <string>
#include <vector>

#include "storage/schema.h"
#include "cli/agent_create.h"

namespace fs = std::filesystem;
namespace sui::quorum::cli {

// Resolve the shipped SKILL.md for a knower specialty. First hit wins:
//   (a) <quorum_root>/templates/skills/<knower>/SKILL.md  (when known)
//   (b) $HOME/.claude/skills/<knower>/SKILL.md            (installed skills)
//   (c) CWD ladder: templates/.. then ../templates/..     (mirrors rubric.h)
// Returns an empty string if none resolve (init must NOT fail on this).
inline std::string resolve_knower_skill(const std::string& quorum_root,
                                        const std::string& knower) {
    if (!quorum_root.empty()) {
        auto p = fs::path(quorum_root) / "templates" / "skills" / knower / "SKILL.md";
        if (fs::exists(p) && fs::is_regular_file(p)) return p.string();
    }
    if (const char* home = std::getenv("HOME")) {
        auto p = fs::path(home) / ".claude" / "skills" / knower / "SKILL.md";
        if (fs::exists(p) && fs::is_regular_file(p)) return p.string();
    }
    const std::vector<fs::path> candidates = {
        fs::path("templates") / "skills" / knower / "SKILL.md",
        fs::path("..") / "templates" / "skills" / knower / "SKILL.md",
    };
    for (const auto& c : candidates) {
        if (fs::exists(c) && fs::is_regular_file(c)) return c.string();
    }
    return "";
}

inline int init_project(const std::string& quorum_root = "") {
    // 1. Check .quorum/ doesn't already exist
    if (fs::exists(".quorum")) {
        std::cerr << "ERROR: already initialized (.quorum/ exists)\n";
        return 1;
    }

    auto cwd = fs::current_path().string();
    std::cout << "Initializing Quorum in " << cwd << "\n";

    // 2. Create directories
    fs::create_directories(".quorum/agents");
    fs::create_directories(".quorum/vaults/leader/knowledge");
    // Project-scope knowledge: rules/refs that apply to ALL agents.
    // Phase 7 Track 2 — context_assembler resolves rules across project,
    // role, and per-agent vault scopes, with the cap operating on the union.
    fs::create_directories(".quorum/knowledge");
    {
        std::ofstream gk(".quorum/knowledge/.gitkeep", std::ios::trunc);
        // Empty file — keeps the directory under version control.
    }

    // Role-scope knowledge (Phase 7 Track 3): rules under
    // .quorum/knowledge/roles/<role>/ apply to every agent of that role.
    // Pre-create one subdir per built-in role so the convention is
    // discoverable from a fresh init.
    static constexpr const char* kRoles[] = {
        "leader", "thinker", "doer", "evaluator",
    };
    for (const auto* role : kRoles) {
        auto dir = std::string(".quorum/knowledge/roles/") + role;
        fs::create_directories(dir);
        std::ofstream gk(dir + "/.gitkeep", std::ios::trunc);
    }

    // 3. Write .quorum/config.yaml
    {
        std::ofstream out(".quorum/config.yaml", std::ios::trunc);
        if (!out.is_open()) {
            std::cerr << "ERROR: cannot write .quorum/config.yaml\n";
            return 1;
        }
        out << "# Quorum Project Configuration\n"
            << "# Generated by quorum init\n"
            << "\n"
            << "daemon:\n"
            << "  data_dir: .quorum\n"
            << "  pid_file: .quorum/quorum.pid\n"
            << "\n"
            << "budget:\n"
            << "  window_budget_usd: 100.00\n"
            << "  window_hours: 5\n"
            << "\n"
            << "conversations:\n"
            << "  enabled: true\n"
            << "  default_max_rounds: 20\n"
            << "  leader: leader\n";
    }
    std::cout << "  Created: .quorum/config.yaml\n";

    // 4. Write .quorum/agents/leader.yaml
    {
        std::ofstream out(".quorum/agents/leader.yaml", std::ios::trunc);
        if (!out.is_open()) {
            std::cerr << "ERROR: cannot write .quorum/agents/leader.yaml\n";
            return 1;
        }
        out << "id: leader\n"
            << "name: \"Leader\"\n"
            << "role: leader\n"
            << "description: \"Coordinates the team -- receives goals, routes work to thinkers/knowers/doers\"\n"
            << "\n"
            << "vault_path: .quorum/vaults/leader/\n"
            << "context_file: .quorum/vaults/leader/CONTEXT.md\n";
    }
    std::cout << "  Created: .quorum/agents/leader.yaml\n";

    // 5. Write .quorum/vaults/leader/CONTEXT.md
    {
        std::ofstream out(".quorum/vaults/leader/CONTEXT.md", std::ios::trunc);
        if (!out.is_open()) {
            std::cerr << "ERROR: cannot write .quorum/vaults/leader/CONTEXT.md\n";
            return 1;
        }
        out << "# Leader Agent\n"
            << "\n"
            << "## Role\n"
            << "\n"
            << "You are the **Leader**. You receive the user's goal, break it into steps,\n"
            << "and route work to the right agent via HANDOFF blocks.\n"
            << "\n"
            << "## What You Do\n"
            << "\n"
            << "1. Receive the goal from the user.\n"
            << "2. Decide which agent should handle the next step.\n"
            << "3. Route via a HANDOFF block with a clear, actionable prompt.\n"
            << "4. When the goal is complete, HANDOFF to `done` to finish the conversation.\n"
            << "\n"
            << "## What You Do NOT Do\n"
            << "\n"
            << "- Do NOT write code yourself.\n"
            << "- Do NOT plan in excessive detail -- delegate to thinker agents.\n"
            << "- Do NOT accumulate knowledge yourself -- the knowers (cartographer/architect/historian/recap) are the sole accumulators.\n"
            << "\n"
            << "## When Stuck\n"
            << "\n"
            << "If you need clarification or cannot proceed, HANDOFF to `human` with a\n"
            << "clear question explaining what you need.\n";
    }
    std::cout << "  Created: .quorum/vaults/leader/CONTEXT.md\n";

    // 6. Write .quorum/.gitignore
    {
        std::ofstream out(".quorum/.gitignore", std::ios::trunc);
        if (!out.is_open()) {
            std::cerr << "ERROR: cannot write .quorum/.gitignore\n";
            return 1;
        }
        out << "# Quorum runtime data -- regenerated by daemon\n"
            << "quorum.db\n"
            << "quorum.db-wal\n"
            << "quorum.db-shm\n"
            << "quorum.pid\n"
            << "vaults/*/knowledge/\n"
            << "\n"
            << "# Keep: config.yaml, agents/\n";
    }
    std::cout << "  Created: .quorum/.gitignore\n";

    // 6a. Create quorum.db with schema
    {
        sui::quorum::Database db(".quorum/quorum.db");
        if (db.is_open()) {
            sui::quorum::create_schema(db);
            std::cout << "  Created: .quorum/quorum.db\n";
        }
    }

    // 6b. Scaffold the rest of the default roster (definitions only — no
    // Tier-1 scans, no Python tool copies, no recap dump seeding; those stay
    // in scripts/setup-knowers.sh). Every agent is created with no_ai = true
    // so init spends ZERO tokens. CWD is the fresh project, so create_agent
    // discovers THIS .quorum/ via discover_project_root().
    //
    // Generic role: thinker relies on skill auto-detect (OK if it falls back
    // to a generic CONTEXT.md template).
    {
        sui::quorum::cli::AgentCreateParams p;
        p.role = "thinker";
        p.name = "thinker";
        p.no_ai = true;
        sui::quorum::cli::create_agent(p);
    }

    // Knowers: role `thinker` + a specialty SKILL file. Descriptions are
    // byte-identical to scripts/setup-knowers.sh (the source of truth). If a
    // SKILL doesn't resolve, the agent is still created WITHOUT a skill_file
    // and a warning is printed — init must NOT fail on a missing SKILL.
    struct Knower { const char* name; const char* description; };
    static const Knower kKnowers[] = {
        {"cartographer",
         "Cartographer: knows the project layout. Reads the Tier-1 index (.quorum/cartographer/layout.json) + honors the root CLAUDE.md; produces a fast-lookup project index. Read-only."},
        {"architect",
         "Architect: maps component interconnections (imports, cross-repo calls, event flows) with file evidence; traces the primary flow; flags coupling/invariants. Read-only."},
        {"historian",
         "Historian: knows the project's decisions + pivots. Reads the Tier-1 record (.quorum/historian/decisions-raw.json) + the Decision Log; tracks status/supersession with PR/commit provenance. Read-only."},
        {"recap",
         "Recap: knows what changed recently + where you left off (WHAT/WHEN). Reads the Tier-1 windowed timeline (.quorum/recap/timeline-raw.json) + operator-dumped timestamped messages, weaves one dated component-grouped timeline, drafts where-i-left-off, with a by-intent read-only Linear status overlay. Read-only; never queries Linear/Slack/Telegram."},
    };
    for (const auto& k : kKnowers) {
        sui::quorum::cli::AgentCreateParams p;
        p.role = "thinker";
        p.name = k.name;
        p.description = k.description;
        p.no_ai = true;
        p.skill_file = resolve_knower_skill(quorum_root, k.name);
        if (p.skill_file.empty()) {
            std::cout << "  WARNING: " << k.name << " SKILL not found; run "
                      << "scripts/setup-knowers.sh to attach the specialty skill.\n";
        }
        sui::quorum::cli::create_agent(p);
    }

    // 7. Print next steps
    std::cout << "  Created: .quorum/vaults/leader/knowledge/\n";
    std::cout << "  Created: .quorum/knowledge/  "
              << "(project-wide rules and references that apply to all agents)\n";
    std::cout << "  Created: .quorum/knowledge/roles/{leader,thinker,doer,evaluator}/  "
              << "(role-specific rules apply to every agent of that role)\n";
    std::cout << "\nQuorum initialized with 6 agents "
              << "(leader, thinker, cartographer, architect, historian, recap).\n"
              << "Next steps:\n";
    std::cout << "  1. Attach knower specialty skills + Tier-1 scans (token-free):\n";
    std::cout << "     scripts/setup-knowers.sh <project-dir>\n";
    std::cout << "  2. Add more agents (auto-discovered from .quorum/agents/):\n";
    std::cout << "     quorum agent create --role doer --name my-dev\n";
    std::cout << "  3. Start a conversation:\n";
    std::cout << "     quorum converse \"your goal here\"\n";

    return 0;
}

} // namespace sui::quorum::cli
