#pragma once

#include <filesystem>
#include <fstream>
#include <iostream>
#include <string>

namespace fs = std::filesystem;
namespace sui::quorum::cli {

inline int init_project() {
    // 1. Check .quorum/ doesn't already exist
    if (fs::exists(".quorum")) {
        std::cerr << "ERROR: already initialized (.quorum/ exists)\n";
        return 1;
    }

    auto cwd = fs::current_path().string();
    std::cout << "Initializing Quorum in " << cwd << "\n";

    // 2. Create directories
    fs::create_directories(".quorum/agents");
    fs::create_directories(".quorum/vaults/leader/knowledge");
    fs::create_directories(".quorum/teams");

    // 3. Write .quorum/config.yaml
    {
        std::ofstream out(".quorum/config.yaml", std::ios::trunc);
        if (!out.is_open()) {
            std::cerr << "ERROR: cannot write .quorum/config.yaml\n";
            return 1;
        }
        out << "# Quorum Project Configuration\n"
            << "# Generated by quorum init\n"
            << "\n"
            << "daemon:\n"
            << "  data_dir: .quorum\n"
            << "  pid_file: .quorum/quorum.pid\n"
            << "\n"
            << "budget:\n"
            << "  window_budget_usd: 100.00\n"
            << "  window_hours: 5\n"
            << "\n"
            << "conversations:\n"
            << "  enabled: true\n"
            << "  default_max_rounds: 20\n"
            << "  default_budget_usd: 5.0\n"
            << "  leader: leader\n";
    }
    std::cout << "  Created: .quorum/config.yaml\n";

    // 4. Write .quorum/agents/leader.yaml
    {
        std::ofstream out(".quorum/agents/leader.yaml", std::ios::trunc);
        if (!out.is_open()) {
            std::cerr << "ERROR: cannot write .quorum/agents/leader.yaml\n";
            return 1;
        }
        out << "id: leader\n"
            << "name: \"Leader\"\n"
            << "role: leader\n"
            << "description: \"Coordinates the team -- receives goals, routes work, triggers scribe\"\n"
            << "\n"
            << "vault_path: .quorum/vaults/leader/\n"
            << "context_file: .quorum/vaults/leader/CONTEXT.md\n";
    }
    std::cout << "  Created: .quorum/agents/leader.yaml\n";

    // 5. Write .quorum/vaults/leader/CONTEXT.md
    {
        std::ofstream out(".quorum/vaults/leader/CONTEXT.md", std::ios::trunc);
        if (!out.is_open()) {
            std::cerr << "ERROR: cannot write .quorum/vaults/leader/CONTEXT.md\n";
            return 1;
        }
        out << "# Leader Agent\n"
            << "\n"
            << "## Role\n"
            << "\n"
            << "You are the **Leader**. You receive the user's goal, break it into steps,\n"
            << "and route work to the right agent via HANDOFF blocks.\n"
            << "\n"
            << "## What You Do\n"
            << "\n"
            << "1. Receive the goal from the user.\n"
            << "2. Decide which agent should handle the next step.\n"
            << "3. Route via a HANDOFF block with a clear, actionable prompt.\n"
            << "4. When the goal is complete, HANDOFF to `done` to finish the conversation.\n"
            << "\n"
            << "## What You Do NOT Do\n"
            << "\n"
            << "- Do NOT write code yourself.\n"
            << "- Do NOT plan in excessive detail -- delegate to thinker agents.\n"
            << "- Do NOT write documentation -- delegate to scribe agents.\n"
            << "\n"
            << "## When Stuck\n"
            << "\n"
            << "If you need clarification or cannot proceed, HANDOFF to `human` with a\n"
            << "clear question explaining what you need.\n";
    }
    std::cout << "  Created: .quorum/vaults/leader/CONTEXT.md\n";

    // 6. Write .quorum/.gitignore
    {
        std::ofstream out(".quorum/.gitignore", std::ios::trunc);
        if (!out.is_open()) {
            std::cerr << "ERROR: cannot write .quorum/.gitignore\n";
            return 1;
        }
        out << "# Quorum runtime data -- regenerated by daemon\n"
            << "quorum.db\n"
            << "quorum.db-wal\n"
            << "quorum.db-shm\n"
            << "quorum.pid\n"
            << "vaults/*/knowledge/\n"
            << "\n"
            << "# Keep: config.yaml, agents/, teams/\n";
    }
    std::cout << "  Created: .quorum/.gitignore\n";

    // 6b. Write default team preset
    {
        std::ofstream out(".quorum/teams/default.yaml", std::ios::trunc);
        if (!out.is_open()) {
            std::cerr << "ERROR: cannot write .quorum/teams/default.yaml\n";
            return 1;
        }
        out << "name: Default\n"
            << "default_path: [leader]\n";
    }
    std::cout << "  Created: .quorum/teams/default.yaml\n";

    // 7. Print next steps
    std::cout << "  Created: .quorum/vaults/leader/knowledge/\n";
    std::cout << "  Created: .quorum/teams/\n";
    std::cout << "\nQuorum initialized. Next steps:\n";
    std::cout << "  1. Add agents (auto-discovered from .quorum/agents/):\n";
    std::cout << "     quorum agent create --role doer --name my-dev\n";
    std::cout << "  2. Start a conversation:\n";
    std::cout << "     quorum converse \"your goal here\"\n";

    return 0;
}

} // namespace sui::quorum::cli
