# version_stamp.cmake -- stamp the build identity into a generated header.
#
# Invoked by the always-run `quorum_version_stamp` target in
# quorum-core/CMakeLists.txt, NOT only at configure time: a configure-time-only
# stamp keeps printing the sha of whatever tree was checked out the last time
# cmake ran, which is exactly the lie this header exists to prevent.
#
#   cmake -DQ_SRC_DIR=<repo root> -DQ_OUT_FILE=<header> -DQ_VERSION=<x.y.z>
#         [-DQ_FORCE_SHA=<sha>] [-DQ_FORCE_DIRTY=<0|1>]   # test seam only
#         -P version_stamp.cmake
#
# The header is rewritten ONLY when the identity (version, sha, dirty) changed,
# so an unchanged tree never forces a relink. QUORUM_BUILD_UTC therefore records
# when the identity was last stamped -- i.e. the last build that could have
# produced a binary with a different identity.
#
# Q_FORCE_SHA / Q_FORCE_DIRTY exist so the write-side logic (rewrite-on-change,
# skip-on-same) can be exercised without mutating a git tree. Nothing in the
# build passes them; a real build always reads git.

if(NOT DEFINED Q_SRC_DIR OR NOT DEFINED Q_OUT_FILE OR NOT DEFINED Q_VERSION)
    message(FATAL_ERROR
        "version_stamp.cmake: Q_SRC_DIR, Q_OUT_FILE and Q_VERSION are required")
endif()

# ── Read the tree's identity ────────────────────────────────────────────────
set(_sha "unknown")
set(_dirty 0)

if(DEFINED Q_FORCE_SHA)
    set(_sha "${Q_FORCE_SHA}")
    if(DEFINED Q_FORCE_DIRTY AND Q_FORCE_DIRTY)
        set(_dirty 1)
    endif()
else()
    find_package(Git QUIET)
    if(GIT_EXECUTABLE)
        execute_process(
            COMMAND "${GIT_EXECUTABLE}" -C "${Q_SRC_DIR}" rev-parse --short HEAD
            OUTPUT_VARIABLE _rev
            OUTPUT_STRIP_TRAILING_WHITESPACE
            ERROR_QUIET
            RESULT_VARIABLE _rev_rc)
        if(_rev_rc EQUAL 0 AND NOT _rev STREQUAL "")
            set(_sha "${_rev}")
            # Any tracked modification or untracked file counts as dirty: the
            # question this answers is "is the binary the committed tree?".
            execute_process(
                COMMAND "${GIT_EXECUTABLE}" -C "${Q_SRC_DIR}" status --porcelain
                OUTPUT_VARIABLE _porcelain
                OUTPUT_STRIP_TRAILING_WHITESPACE
                ERROR_QUIET
                RESULT_VARIABLE _st_rc)
            if(_st_rc EQUAL 0 AND NOT _porcelain STREQUAL "")
                set(_dirty 1)
            endif()
        endif()
    endif()
endif()

string(TIMESTAMP _utc "%Y-%m-%dT%H:%M:%SZ" UTC)

# ── Compose ─────────────────────────────────────────────────────────────────
# _ident is everything the binary's identity depends on; the UTC line is
# appended separately so it can be stripped for the "did anything change?"
# comparison (otherwise the header would differ on every single build).
set(_ident
"// Generated by quorum-core/src/version_stamp.cmake -- do not edit, do not commit.
// Regenerated on every build; rewritten only when the identity below changes.
#pragma once

#define QUORUM_VERSION   \"${Q_VERSION}\"
#define QUORUM_GIT_SHA   \"${_sha}\"
#define QUORUM_GIT_DIRTY ${_dirty}
")
set(_new "${_ident}#define QUORUM_BUILD_UTC \"${_utc}\"\n")

set(_write TRUE)
if(EXISTS "${Q_OUT_FILE}")
    file(READ "${Q_OUT_FILE}" _old)
    string(REGEX REPLACE "#define QUORUM_BUILD_UTC[^\n]*\n" "" _old_ident "${_old}")
    if("${_old_ident}" STREQUAL "${_ident}")
        set(_write FALSE)
    endif()
endif()

if(_write)
    file(WRITE "${Q_OUT_FILE}" "${_new}")
    set(_suffix "")
    if(_dirty)
        set(_suffix "-dirty")
    endif()
    message(STATUS
        "quorum build identity: ${Q_VERSION} (${_sha}${_suffix}) stamped ${_utc}")
endif()
